### ISSUE TITLE
Use PascalCase :^)

### ISSUE THREAD

**Issue by karroffel** [neikeq/GodotSharp#20]
[Today's your lucky day.](https://www.facebook.com/groups/godotengine/permalink/1063987210404539/)

**Comment by neikeq** [comment]
Great :smiley: We are at the door of alpha though... If we are indeed choosing PascalCasel, it will have to happen after alpha is released.
Well, we could do it for alpha to a certain point, since I already had this prototype from last year before the idea was rejected. In this prototype, calls to virtual methods like _process were redirected to _Process. Then after alpha is released we could tackle the other issues we talked some time ago, like redirecting the rest of API methods, like add_child to AddChild, because the user could override them.
We could still have a class reference in PascalCasel as that would be 
 generated by a tool like Doxygen or Docfx from the method comments we already generate. It would only have the *summary* block though since method comment in Godot don't have return or param categories.

**Comment by zatherz** [comment]
Bump

**Comment by neikeq** [comment]
This is already done. I'll push soon.

**Comment by neikeq** [comment]
Done
