### ISSUE TITLE
Non-C# projects can't be run

### ISSUE THREAD

**Issue by ghost** [neikeq/GodotSharp#50]
The editor complains about not having a C# solution when you try to run a game which doesn't contain any C# code.

**Comment by neikeq** [comment]
What is the error message?

**Comment by NathanWarden** [comment]
I think tagcup is referring the following:

1) Create a new project
2) Create a new scene (rather, add a node and save it)
3) Don't add any C# scripts, don't click Mono>Create C# solution... so there's no C# in the project at all.
4) Try and run
5) "Failed to build project solution"

Maybe if no solution exists when hitting run it should automatically create one? Or, it should be able to know when to completely ignore C# and not even try to build the solution?

I think with either of those the Mono > Create C# Solution button could just go away since creating a C# script automatically creates the solution and if there's no C# it'll just create or ignore it.
